### ISSUE TITLE
'item is unavailable' in playershop

### ISSUE THREAD

**Issue by yello2343** [catch441/Ultimate_Economy#21]
Hey catch, I wanted to let you know I'm having an issue with the playershop. I'll make a shop, add items in the 'editShop' but when my friends try to buy, an item The shop says 'this item is unavailable' It does it for every item I have added.

**Comment by MrFindus** [comment]
Maybe you need to add stock in your shop.

**Comment by yello2343** [comment]
I keep trying but it's not working. I middle click with my mouse and try to add items. I'm not sure what I am doing wrong.

**Comment by catch441** [comment]
you have to sell your items to your shop. you as owner did not pay for that.
