### ISSUE TITLE
Zombies can attack shops and jobcenters

### ISSUE THREAD

**Issue by Kiskadee-dev** [catch441/Ultimate_Economy#63]
The shops can be dragged to very far away.

**To reproduce**
Spawn zombies near some shop or jobcenter

**Expected behaviour**
Static shops

**Environment**
Paper 1.15.2

![2020-03-13_12 46 05](https://user-images.githubusercontent.com/10299707/76646484-cc19b700-6539-11ea-8afa-011cc4a0448c.png)

**Comment by catch441** [comment]
When I switch to static villagers then the villager has no AI. He didn't move, don't turn his head and will make no sounds. Thats the only way I found to make the villager static. For me it is a bad solution. At the moment there is no good solution for this issue.

**Comment by Kiskadee-dev** [comment]
For this specific issue, making them invulnerable does it. Zombies will ignore them. the AI will still work

#62 

Something more fancy would require rewriting part of the villager AI tho
