### ISSUE TITLE
Potions issue of night vision on the admin shop[Bug]

### ISSUE THREAD

**Issue by birdup000** [catch441/Ultimate_Economy#64]
**Describe the bug**

**To Reproduce**
Did you changed the savefiles by yourselfe?
Any error in the server log? (Add server log)
Steps to reproduce.

**Expected behavior**

**Screenshots**

**Environment**
 Bukkit/Spigot/Paper ...
 Server version
 Plugin version

**Additional context**

it won't show up on the admin shop

**Comment by catch441** [comment]
I could not reproduce the issue. Do you use the command or the editor gui?

**Comment by birdup000** [comment]
I used the Command it does not work but I used the GUI editor and it works thank you for replying

**Comment by catch441** [comment]
Thanks for the information

**Comment by catch441** [comment]
cannot be reproduced
