### ISSUE TITLE
add/update to 1.15.2 Spigot[Feature]

### ISSUE THREAD

**Issue by notyourneighbour** [catch441/Ultimate_Economy#73]
**Is your feature request related to a problem? Please describe.**
My problem is that i want to play 1.15.2 with your beautiful economy plugin, but the problem is,
that it doesnt work for 1.15.2

**Describe the solution you'd like**
Update to/for 1.15.2 Spigot/Bukkit?

**Comment by catch441** [comment]
1.15.2 is already supported. What is not working? Any error on startup in the server log?
