### ISSUE TITLE
Can't set or take away Money

### ISSUE THREAD

**Issue by Xahv** [catch441/Ultimate_Economy#81]
There is no way to set a player's money, or take it away. There is only a command to add money. One of my idiot friends got ahold of op perms, so he gave himself essentially infinite money. We are trying to reset everything, and are finding that there is no command to lower money. Only to add. We even tried buying an item that had huge value, but his high money seems to be bugging out.

**Comment by catch441** [comment]
you can use /givemoney player -1000
