### ISSUE TITLE
[Bug] Cannot quit jobs or change job limit

### ISSUE THREAD

**Issue by topdude15** [catch441/Ultimate_Economy#82]
There does not appear to be a command for admins or players to quit a job or to change the maximum number of jobs that a player can have.  I have many jobs on my server and I want players to be able to switch between any of them, so some way to quit a job is essential.

**Comment by catch441** [comment]
they can quit with the jobcenter. Idk if it was a left or right click on the job. And you can change the max jobs with /ue-config maxJobs <number>
