### ISSUE TITLE
[Question]Spawner Shop

### ISSUE THREAD

**Issue by Xahv** [catch441/Ultimate_Economy#83]
I created a Spawner Shop, by using /adminshop addSpawner, but when I buy spawners, they are all default pig spawners. I suspect this is to do with a custom spawners plugin interfering with the shop.
Is this a problem with my other plugins? If so, how can I fix it?

**Comment by catch441** [comment]
you have to place the spawners in survival mode

**Comment by ProtocolKiller** [comment]
> you have to place the spawners in survival mode i did that and it didnt work is this a bug at the moment?

**Comment by catch441** [comment]
cannot be reproduced
