### ISSUE TITLE
Shop commands will not work

### ISSUE THREAD

**Issue by donutgoose** [catch441/Ultimate_Economy#90]
The shop commands wont work. When I type /playershop delete SHOPNAME (well pretend my shop is called shopname) it will say SHOPNAME_MYUSERNAME does not exist (MYUSERNAME is going to be a placeholer for my username) Can anyone help?

**Comment by catch441** [comment]
did you own the shop? If not, you can use /playershop deleteOther shopname_playername

**Comment by catch441** [comment]
cannot be reproduced with 1.2.6
