### ISSUE TITLE
adminshop not allowing me to buy/sell [Bug]

### ISSUE THREAD

**Issue by risocat** [catch441/Ultimate_Economy#92]
Occasionally, when I try to access an adminshop, either in person or via `/shop [shopname]`, the shop will behave as if it were only a chest. I can still see the prices when hovering over it, but when I'm clicking or right clicking on items in the shop inventory or my own inventory, it just acts like a chest. I'm using this plugin on a Minehut server in 1.15.2.

Thank you for such a fun plugin! I'm building out an economy/world with my friends to escape the real world.

**Comment by catch441** [comment]
cannot be reproduced with 1.2.6
