### ISSUE TITLE
Ultimate Economy error while enabling [Bug]

### ISSUE THREAD

**Issue by SizzledkPulse** [catch441/Ultimate_Economy#94]
Hey there ! I'm facing an error with ue on a server. Hope you might help me on this

Error occurred while enabling Ultimate_Economy v1.2.5f

This errors occured after a server auto reboot
Server is on Paper version
ue commands doesn't work

Here is the server log :
[message.txt](https://github.com/catch441/Ultimate_Economy/files/4677409/message.txt)

Plugin was removed then added again with same results.

Thanks for your help !

**Comment by catch441** [comment]
One of your adminshops is the problem. Try to delete the adminshop savefiles and the shopname from the config and create them again. Did you add any special item to a asminshop?
