### ISSUE TITLE
[Enhancement]jobcenter job addBreedable <mob> <payment>

### ISSUE THREAD

**Issue by CowedOffACliff** [catch441/Ultimate_Economy#97]
This is a request for a job line item for breeding pairs of mobs together. A successful breeding attempt would reward currency.

jobcenter job addBreedable <mob> <payment>
jobcenter job removeBreedable <mob>
jobcenter job updateBreedable <mob> <payment>

The Bukkit API has this for handling breeding events:
[https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityBreedEvent.html](url)

IF NOT event.isCancelled()
    IF joblist contains entityX for event.getEntity() AND event.getBreeder() == Player AND Player has job to breed entityX
     THEN event.getBreeder().ecoPlayer.increasePlayerAmount(price, false)

**Comment by CowedOffACliff** [comment]
I set up an environment in Eclipse and attempted to write the code for this because I figured it would be relatively simple to add. I haven't coded in many years and I've never done anything but Bukkit only with Forge, but it went well. If I can get time this week I may be able to finish the function and have it working.

**Comment by catch441** [comment]
nice job

**Comment by catch441** [comment]
added with 1.2.6
