### ISSUE TITLE
[Bug]Updating to next version could break everyone's server files

### ISSUE THREAD

**Issue by CowedOffACliff** [catch441/Ultimate_Economy#98]
**Bug:**
When you attempt to update the plugin to the version that's currently in dev branch (call it 1.2.6) it fails to load the player file correctly which causes it to crash the plugin while simultaneously corrupting any existing shop and job files. There is a mismatch of the player Ibans between these two versions which is having some impact on the file loader. When it tries to match the Ibans in the pre-existing player file it hits null data somewhere and wrecks itself.

**To Reproduce**
1. Create a server using jar version 1.2.5f. Load up the server and do something like give yourself money in order to generate and populate all of the basic files pertaining to player identification and bank data storage.

2. Now that you have a populated player data file open the file and take note of the Iban identifier corresponding to your player character.

3. Now that you have some pre-existing data remove the 1.2.5f jarfile and replace it with a new version of the plugin (1.2.6) compiled from dev branch.
4. Load up the server again with the new plugin and it will spew a stack trace into the console, fail to initialize the plugin, then spew another stack trace when it also fails to disable the plugin. All of the stack traces seem to point towards player Iban data interpretation as the source of the problem.
5. Delete all of the config data for the plugin and then restart the server. The plugin will now load correctly.
6. Load up the server again and then perform steps to regenerate and repopulate the player data files again. Open up the player data and take note of the Iban value. The Iban will be different than it was when running the 1.2.5f version of the jar.

**Expected behavior**
Server operators are going to expect to be able to just copy in the next version of the plugin without it corrupting all of their pre-existing player data and corrupting jobfiles.

**Environment**
Paper server 1.15.2.
Plugin versions 1.2.5f -> 1.2.6 (dev)

**Additional context**
I've reproduced this bug twice so far; once on my live server and once on my test server. The results and symptoms were identical both times.

**Comment by catch441** [comment]
Thanks for the information. At the moment I add unit tests to test the entire plugin with some code. I will look into the iban system and check this bug

**Comment by CowedOffACliff** [comment]
I have some new information on this bug after I finally got my local build environment sorted out again.

It appears that the iban failure is caused by a null value being passed to the thrown GeneralEconomyException causing it to crash the plugin as a null value instead of a caught exception.
The reason this appears to be happening in my test environment is because for some reason my PlayerFile.yml contains player names in the Player: category that have no bank account information associated with the name. This means no legacy information or new Iban information. Because the lookup can find neither it checks for a null value and crashes on an NPE. The solution for this is to catch the NPE and reset that username with new account information.

I have local changes anyway so I will probably attempt to modify this code and get the bug cleaned up using my already broken environment

**Comment by CowedOffACliff** [comment]
Pull request #99 now contains some new code that should fix this issue going forward. In my own local malformed environment I was able to get it to handle my PlayerFile and reload all players with new ibans including 0 value ibans for players with no pre-existing accounts. Should be good to go but I'll probably attempt to push this to my live server as a final test.

**Comment by catch441** [comment]
thanks, is implemented
